# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_win.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from img_rcc import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1150, 545)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.r_tab = QtWidgets.QWidget()
        self.r_tab.setObjectName("r_tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.r_tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.r_tw = QtWidgets.QTableWidget(self.r_tab)
        self.r_tw.setMouseTracking(True)
        self.r_tw.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.r_tw.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.r_tw.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.r_tw.setObjectName("r_tw")
        self.r_tw.setColumnCount(13)
        self.r_tw.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.r_tw.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.r_tw.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.r_tw.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.r_tw.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.r_tw.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.r_tw.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.r_tw.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.r_tw.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.r_tw.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.r_tw.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.r_tw.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.r_tw.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.r_tw.setHorizontalHeaderItem(12, item)
        self.gridLayout_2.addWidget(self.r_tw, 0, 0, 1, 1)
        self.tabWidget.addTab(self.r_tab, "")
        self.b_tab = QtWidgets.QWidget()
        self.b_tab.setObjectName("b_tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.b_tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.b_tw = QtWidgets.QTableWidget(self.b_tab)
        self.b_tw.setMouseTracking(True)
        self.b_tw.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.b_tw.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.b_tw.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.b_tw.setObjectName("b_tw")
        self.b_tw.setColumnCount(14)
        self.b_tw.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.b_tw.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.b_tw.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.b_tw.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.b_tw.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.b_tw.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.b_tw.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.b_tw.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.b_tw.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.b_tw.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.b_tw.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.b_tw.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.b_tw.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.b_tw.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.b_tw.setHorizontalHeaderItem(13, item)
        self.gridLayout_3.addWidget(self.b_tw, 0, 0, 1, 1)
        self.tabWidget.addTab(self.b_tab, "")
        self.rt_tab = QtWidgets.QWidget()
        self.rt_tab.setObjectName("rt_tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.rt_tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.rt_tw = QtWidgets.QTableWidget(self.rt_tab)
        self.rt_tw.setMouseTracking(True)
        self.rt_tw.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.rt_tw.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.rt_tw.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.rt_tw.setObjectName("rt_tw")
        self.rt_tw.setColumnCount(7)
        self.rt_tw.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.rt_tw.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.rt_tw.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.rt_tw.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.rt_tw.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.rt_tw.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.rt_tw.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.rt_tw.setHorizontalHeaderItem(6, item)
        self.gridLayout_4.addWidget(self.rt_tw, 0, 0, 1, 1)
        self.tabWidget.addTab(self.rt_tab, "")
        self.br_tab = QtWidgets.QWidget()
        self.br_tab.setObjectName("br_tab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.br_tab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.br_tw = QtWidgets.QTableWidget(self.br_tab)
        self.br_tw.setMouseTracking(True)
        self.br_tw.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.br_tw.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.br_tw.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.br_tw.setObjectName("br_tw")
        self.br_tw.setColumnCount(13)
        self.br_tw.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.br_tw.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.br_tw.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.br_tw.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.br_tw.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.br_tw.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.br_tw.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.br_tw.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.br_tw.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.br_tw.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.br_tw.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.br_tw.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.br_tw.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.br_tw.setHorizontalHeaderItem(12, item)
        self.gridLayout_6.addWidget(self.br_tw, 0, 0, 1, 1)
        self.tabWidget.addTab(self.br_tab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.rd_query = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icon/query.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rd_query.setIcon(icon)
        self.rd_query.setObjectName("rd_query")
        self.rd_insert = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icon/insert.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rd_insert.setIcon(icon1)
        self.rd_insert.setObjectName("rd_insert")
        self.action_update = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icon/undate.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_update.setIcon(icon2)
        self.action_update.setObjectName("action_update")
        self.action_room = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icon/room.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_room.setIcon(icon3)
        self.action_room.setObjectName("action_room")
        self.action_borrow = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Icon/borrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_borrow.setIcon(icon4)
        self.action_borrow.setObjectName("action_borrow")
        self.action_return = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Icon/return.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_return.setIcon(icon5)
        self.action_return.setObjectName("action_return")
        self.toolBar.addAction(self.rd_query)
        self.toolBar.addAction(self.rd_insert)
        self.toolBar.addAction(self.action_borrow)
        self.toolBar.addAction(self.action_return)
        self.toolBar.addAction(self.action_update)
        self.toolBar.addAction(self.action_room)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "图书管理系统"))
        item = self.r_tw.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "编号"))
        item = self.r_tw.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "姓名"))
        item = self.r_tw.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "性别"))
        item = self.r_tw.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "类别"))
        item = self.r_tw.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "单位名称"))
        item = self.r_tw.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "电话号码"))
        item = self.r_tw.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "电子邮箱"))
        item = self.r_tw.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "登记日期"))
        item = self.r_tw.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "读者照片"))
        item = self.r_tw.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "证件状态"))
        item = self.r_tw.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "已借数量"))
        item = self.r_tw.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "读者密码"))
        item = self.r_tw.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "管理角色"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.r_tab), _translate("MainWindow", "读者信息"))
        item = self.b_tw.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "序号"))
        item = self.b_tw.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "编号"))
        item = self.b_tw.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "书名"))
        item = self.b_tw.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "作者"))
        item = self.b_tw.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "出版社"))
        item = self.b_tw.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "出版日期"))
        item = self.b_tw.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "ISBN书号"))
        item = self.b_tw.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "语言"))
        item = self.b_tw.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "页数"))
        item = self.b_tw.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "价钱"))
        item = self.b_tw.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "入馆时间"))
        item = self.b_tw.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "内容简介"))
        item = self.b_tw.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "图书封面照片"))
        item = self.b_tw.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "图书状态"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.b_tab), _translate("MainWindow", "图书信息"))
        item = self.rt_tw.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "类型"))
        item = self.rt_tw.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "名称"))
        item = self.rt_tw.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "可借数量"))
        item = self.rt_tw.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "可借天数"))
        item = self.rt_tw.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "可续借次数"))
        item = self.rt_tw.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "罚款率（元/天）"))
        item = self.rt_tw.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "证书有效期（年）"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.rt_tab), _translate("MainWindow", "读者类型信息"))
        item = self.br_tw.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "借书顺序号"))
        item = self.br_tw.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "读者编号"))
        item = self.br_tw.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "图书序号"))
        item = self.br_tw.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "续借次数"))
        item = self.br_tw.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "借书日期"))
        item = self.br_tw.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "应还日期"))
        item = self.br_tw.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "实际还书日期"))
        item = self.br_tw.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "超期天数"))
        item = self.br_tw.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "超期金额"))
        item = self.br_tw.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "罚款金额"))
        item = self.br_tw.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "是否还书"))
        item = self.br_tw.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "借书操作员"))
        item = self.br_tw.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "还书操作员"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.br_tab), _translate("MainWindow", "借阅信息"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.rd_query.setText(_translate("MainWindow", "查询"))
        self.rd_insert.setText(_translate("MainWindow", "添加"))
        self.action_update.setText(_translate("MainWindow", "同步"))
        self.action_update.setToolTip(_translate("MainWindow", "同步"))
        self.action_update.setShortcut(_translate("MainWindow", "F5"))
        self.action_room.setText(_translate("MainWindow", "个人中心"))
        self.action_room.setToolTip(_translate("MainWindow", "个人中心"))
        self.action_borrow.setText(_translate("MainWindow", "借书"))
        self.action_return.setText(_translate("MainWindow", "还书"))
