from PyQt5 import QtCore, QtGui, QtWidgets
from img_rcc import *

class Ui_login_Form(object):
    def setupUi(self, login_Form):
        login_Form.setObjectName("login_Form")
        login_Form.resize(280, 277)
        self.gridLayout_2 = QtWidgets.QGridLayout(login_Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lib_le = QtWidgets.QLabel(login_Form)
        self.lib_le.setText("")
        self.lib_le.setPixmap(QtGui.QPixmap(":/Icon/lib.png"))
        self.lib_le.setAlignment(QtCore.Qt.AlignCenter)
        self.lib_le.setObjectName("lib_le")
        self.gridLayout.addWidget(self.lib_le, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(login_Form)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/Icon/user.png"))
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(login_Form)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/Icon/password.png"))
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.user_le = QtWidgets.QLineEdit(login_Form)
        self.user_le.setObjectName("user_le")
        self.verticalLayout_2.addWidget(self.user_le)
        self.password_le = QtWidgets.QLineEdit(login_Form)
        self.password_le.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_le.setObjectName("password_le")
        self.verticalLayout_2.addWidget(self.password_le)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.login_btn = QtWidgets.QPushButton(login_Form)
        self.login_btn.setObjectName("login_btn")
        self.horizontalLayout_2.addWidget(self.login_btn)
        self.re_btn = QtWidgets.QPushButton(login_Form)
        self.re_btn.setObjectName("re_btn")
        self.horizontalLayout_2.addWidget(self.re_btn)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.prompt_le = QtWidgets.QLabel(login_Form)
        self.prompt_le.setAlignment(QtCore.Qt.AlignCenter)
        self.prompt_le.setObjectName("prompt_le")
        self.gridLayout.addWidget(self.prompt_le, 3, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(login_Form)
        self.re_btn.clicked.connect(self.user_le.clear)
        self.re_btn.clicked.connect(self.password_le.clear)
        QtCore.QMetaObject.connectSlotsByName(login_Form)

    def retranslateUi(self, login_Form):
        _translate = QtCore.QCoreApplication.translate
        login_Form.setWindowTitle(_translate("login_Form", "用户登录"))
        self.user_le.setPlaceholderText(_translate("login_Form", "读者编号/借书证号"))
        self.password_le.setPlaceholderText(_translate("login_Form", "密码"))
        self.login_btn.setText(_translate("login_Form", "登陆"))
        self.re_btn.setText(_translate("login_Form", "重置"))
        self.prompt_le.setText(_translate("login_Form", "欢迎登陆图书管理系统！"))

class Ui_user_room_Form(object):
    def setupUi(self, user_room_Form):
        user_room_Form.setObjectName("user_room_Form")
        user_room_Form.resize(427, 251)
        self.gridLayout = QtWidgets.QGridLayout(user_room_Form)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.user_photo = QtWidgets.QLabel(user_room_Form)
        self.user_photo.setFrameShape(QtWidgets.QFrame.Box)
        self.user_photo.setText("")
        self.user_photo.setPixmap(QtGui.QPixmap(":/Icon/load.png"))
        self.user_photo.setAlignment(QtCore.Qt.AlignCenter)
        self.user_photo.setObjectName("user_photo")
        self.horizontalLayout_2.addWidget(self.user_photo)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(user_room_Form)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(user_room_Form)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(user_room_Form)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_11 = QtWidgets.QLabel(user_room_Form)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.label_4 = QtWidgets.QLabel(user_room_Form)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(user_room_Form)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(user_room_Form)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(user_room_Form)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_9 = QtWidgets.QLabel(user_room_Form)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(user_room_Form)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.label_12 = QtWidgets.QLabel(user_room_Form)
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.id = QtWidgets.QLabel(user_room_Form)
        self.id.setObjectName("id")
        self.verticalLayout_2.addWidget(self.id)
        self.name = QtWidgets.QLabel(user_room_Form)
        self.name.setObjectName("name")
        self.verticalLayout_2.addWidget(self.name)
        self.sex = QtWidgets.QLabel(user_room_Form)
        self.sex.setObjectName("sex")
        self.verticalLayout_2.addWidget(self.sex)
        self.type = QtWidgets.QLabel(user_room_Form)
        self.type.setObjectName("type")
        self.verticalLayout_2.addWidget(self.type)
        self.dept = QtWidgets.QLabel(user_room_Form)
        self.dept.setObjectName("dept")
        self.verticalLayout_2.addWidget(self.dept)
        self.phone = QtWidgets.QLabel(user_room_Form)
        self.phone.setObjectName("phone")
        self.verticalLayout_2.addWidget(self.phone)
        self.email = QtWidgets.QLabel(user_room_Form)
        self.email.setObjectName("email")
        self.verticalLayout_2.addWidget(self.email)
        self.date = QtWidgets.QLabel(user_room_Form)
        self.date.setObjectName("date")
        self.verticalLayout_2.addWidget(self.date)
        self.status = QtWidgets.QLabel(user_room_Form)
        self.status.setObjectName("status")
        self.verticalLayout_2.addWidget(self.status)
        self.qty = QtWidgets.QLabel(user_room_Form)
        self.qty.setObjectName("qty")
        self.verticalLayout_2.addWidget(self.qty)
        self.roles = QtWidgets.QLabel(user_room_Form)
        self.roles.setObjectName("roles")
        self.verticalLayout_2.addWidget(self.roles)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.psw_change_btn = QtWidgets.QPushButton(user_room_Form)
        self.psw_change_btn.setObjectName("psw_change_btn")
        self.verticalLayout_3.addWidget(self.psw_change_btn)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 1)

        self.retranslateUi(user_room_Form)
        QtCore.QMetaObject.connectSlotsByName(user_room_Form)

    def retranslateUi(self, user_room_Form):
        _translate = QtCore.QCoreApplication.translate
        user_room_Form.setWindowTitle(_translate("user_room_Form", "个人中心"))
        self.label.setText(_translate("user_room_Form", "编号："))
        self.label_2.setText(_translate("user_room_Form", "姓名："))
        self.label_3.setText(_translate("user_room_Form", "性别："))
        self.label_11.setText(_translate("user_room_Form", "类别："))
        self.label_4.setText(_translate("user_room_Form", "单位名称："))
        self.label_5.setText(_translate("user_room_Form", "电话号码："))
        self.label_6.setText(_translate("user_room_Form", "电子邮箱："))
        self.label_7.setText(_translate("user_room_Form", "登记日期："))
        self.label_9.setText(_translate("user_room_Form", "证件状态："))
        self.label_10.setText(_translate("user_room_Form", "已借数量："))
        self.label_12.setText(_translate("user_room_Form", "管理角色："))
        self.id.setText(_translate("user_room_Form", "..."))
        self.name.setText(_translate("user_room_Form", "..."))
        self.sex.setText(_translate("user_room_Form", "..."))
        self.type.setText(_translate("user_room_Form", "..."))
        self.dept.setText(_translate("user_room_Form", "..."))
        self.phone.setText(_translate("user_room_Form", "..."))
        self.email.setText(_translate("user_room_Form", "..."))
        self.date.setText(_translate("user_room_Form", "..."))
        self.status.setText(_translate("user_room_Form", "..."))
        self.qty.setText(_translate("user_room_Form", "..."))
        self.roles.setText(_translate("user_room_Form", "..."))
        self.psw_change_btn.setText(_translate("user_room_Form", "更换密码"))

class Ui_psw_change_Form(object):
    def setupUi(self, psw_change_Form):
        psw_change_Form.setObjectName("psw_change_Form")
        psw_change_Form.resize(265, 125)
        self.gridLayout = QtWidgets.QGridLayout(psw_change_Form)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(psw_change_Form)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(psw_change_Form)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(psw_change_Form)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.old_psw_le = QtWidgets.QLineEdit(psw_change_Form)
        self.old_psw_le.setMaxLength(20)
        self.old_psw_le.setEchoMode(QtWidgets.QLineEdit.Password)
        self.old_psw_le.setObjectName("old_psw_le")
        self.verticalLayout_2.addWidget(self.old_psw_le)
        self.new_psw_le = QtWidgets.QLineEdit(psw_change_Form)
        self.new_psw_le.setMaxLength(20)
        self.new_psw_le.setEchoMode(QtWidgets.QLineEdit.Password)
        self.new_psw_le.setObjectName("new_psw_le")
        self.verticalLayout_2.addWidget(self.new_psw_le)
        self.check_psw_le = QtWidgets.QLineEdit(psw_change_Form)
        self.check_psw_le.setMaxLength(20)
        self.check_psw_le.setEchoMode(QtWidgets.QLineEdit.Password)
        self.check_psw_le.setObjectName("check_psw_le")
        self.verticalLayout_2.addWidget(self.check_psw_le)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.old_psw_echo = QtWidgets.QLabel(psw_change_Form)
        self.old_psw_echo.setObjectName("old_psw_echo")
        self.verticalLayout_3.addWidget(self.old_psw_echo)
        self.new_psw_echo = QtWidgets.QLabel(psw_change_Form)
        self.new_psw_echo.setObjectName("new_psw_echo")
        self.verticalLayout_3.addWidget(self.new_psw_echo)
        self.check_psw_echo = QtWidgets.QLabel(psw_change_Form)
        self.check_psw_echo.setObjectName("check_psw_echo")
        self.verticalLayout_3.addWidget(self.check_psw_echo)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.psw_change_btn = QtWidgets.QPushButton(psw_change_Form)
        self.psw_change_btn.setObjectName("psw_change_btn")
        self.verticalLayout_4.addWidget(self.psw_change_btn)
        self.gridLayout.addLayout(self.verticalLayout_4, 0, 0, 1, 1)

        self.retranslateUi(psw_change_Form)
        QtCore.QMetaObject.connectSlotsByName(psw_change_Form)

    def retranslateUi(self, psw_change_Form):
        _translate = QtCore.QCoreApplication.translate
        psw_change_Form.setWindowTitle(_translate("psw_change_Form", "更换密码"))
        self.label.setText(_translate("psw_change_Form", "旧密码："))
        self.label_2.setText(_translate("psw_change_Form", "新密码："))
        self.label_3.setText(_translate("psw_change_Form", "再次确认："))
        self.old_psw_echo.setText(_translate("psw_change_Form", "..."))
        self.new_psw_echo.setText(_translate("psw_change_Form", "..."))
        self.check_psw_echo.setText(_translate("psw_change_Form", "..."))
        self.psw_change_btn.setText(_translate("psw_change_Form", "更换密码"))

class Ui_r_query_Form(object):
    def setupUi(self, r_query_Form):
        r_query_Form.setObjectName("r_query_Form")
        r_query_Form.resize(300, 45)
        r_query_Form.setAccessibleName("")
        self.gridLayout_3 = QtWidgets.QGridLayout(r_query_Form)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.query_cb = QtWidgets.QComboBox(r_query_Form)
        self.query_cb.setObjectName("query_cb")
        self.query_cb.addItem("")
        self.query_cb.addItem("")
        self.horizontalLayout.addWidget(self.query_cb)
        self.query_le = QtWidgets.QLineEdit(r_query_Form)
        self.query_le.setText("")
        self.query_le.setObjectName("query_le")
        self.horizontalLayout.addWidget(self.query_le)
        self.query_bn = QtWidgets.QPushButton(r_query_Form)
        self.query_bn.setObjectName("query_bn")
        self.horizontalLayout.addWidget(self.query_bn)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)

        self.retranslateUi(r_query_Form)
        QtCore.QMetaObject.connectSlotsByName(r_query_Form)

    def retranslateUi(self, r_query_Form):
        _translate = QtCore.QCoreApplication.translate
        r_query_Form.setWindowTitle(_translate("r_query_Form", "查询"))
        self.query_cb.setItemText(0, _translate("r_query_Form", "编号"))
        self.query_cb.setItemText(1, _translate("r_query_Form", "姓名"))
        self.query_bn.setText(_translate("r_query_Form", "搜索"))

class Ui_br_query_Form(object):
    def setupUi(self, br_query_Form):
        br_query_Form.setObjectName("br_query_Form")
        br_query_Form.resize(400, 91)
        self.gridLayout = QtWidgets.QGridLayout(br_query_Form)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.query_cb = QtWidgets.QComboBox(br_query_Form)
        self.query_cb.setObjectName("query_cb")
        self.query_cb.addItem("")
        self.query_cb.addItem("")
        self.horizontalLayout.addWidget(self.query_cb)
        self.query_le = QtWidgets.QLineEdit(br_query_Form)
        self.query_le.setText("")
        self.query_le.setObjectName("query_le")
        self.horizontalLayout.addWidget(self.query_le)
        self.query_bn = QtWidgets.QPushButton(br_query_Form)
        self.query_bn.setObjectName("query_bn")
        self.horizontalLayout.addWidget(self.query_bn)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.all_rb = QtWidgets.QRadioButton(br_query_Form)
        self.all_rb.setChecked(True)
        self.all_rb.setObjectName("all_rb")
        self.verticalLayout.addWidget(self.all_rb)
        self.notre_rb = QtWidgets.QRadioButton(br_query_Form)
        self.notre_rb.setObjectName("notre_rb")
        self.verticalLayout.addWidget(self.notre_rb)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)

        self.retranslateUi(br_query_Form)
        QtCore.QMetaObject.connectSlotsByName(br_query_Form)

    def retranslateUi(self, br_query_Form):
        _translate = QtCore.QCoreApplication.translate
        br_query_Form.setWindowTitle(_translate("br_query_Form", "查询"))
        self.query_cb.setItemText(0, _translate("br_query_Form", "读者编号"))
        self.query_cb.setItemText(1, _translate("br_query_Form", "图书序号"))
        self.query_bn.setText(_translate("br_query_Form", "搜索"))
        self.all_rb.setText(_translate("br_query_Form", "查询全部记录"))
        self.notre_rb.setText(_translate("br_query_Form", "查询未还记录"))

class Ui_r_br_query_Form(object):
    def setupUi(self, r_br_query_Form):
        r_br_query_Form.setObjectName("r_br_query_Form")
        r_br_query_Form.resize(400, 129)
        self.gridLayout = QtWidgets.QGridLayout(r_br_query_Form)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(r_br_query_Form)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.query_le = QtWidgets.QLineEdit(r_br_query_Form)
        self.query_le.setText("")
        self.query_le.setObjectName("query_le")
        self.horizontalLayout.addWidget(self.query_le)
        self.query_bn = QtWidgets.QPushButton(r_br_query_Form)
        self.query_bn.setObjectName("query_bn")
        self.horizontalLayout.addWidget(self.query_bn)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.all_rb = QtWidgets.QRadioButton(r_br_query_Form)
        self.all_rb.setChecked(True)
        self.all_rb.setObjectName("all_rb")
        self.verticalLayout.addWidget(self.all_rb)
        self.notre_rb = QtWidgets.QRadioButton(r_br_query_Form)
        self.notre_rb.setObjectName("notre_rb")
        self.verticalLayout.addWidget(self.notre_rb)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.line = QtWidgets.QFrame(r_br_query_Form)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.q_all_btn = QtWidgets.QPushButton(r_br_query_Form)
        self.q_all_btn.setObjectName("q_all_btn")
        self.verticalLayout_2.addWidget(self.q_all_btn)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)

        self.retranslateUi(r_br_query_Form)
        QtCore.QMetaObject.connectSlotsByName(r_br_query_Form)

    def retranslateUi(self, r_br_query_Form):
        _translate = QtCore.QCoreApplication.translate
        r_br_query_Form.setWindowTitle(_translate("r_br_query_Form", "查询"))
        self.label.setText(_translate("r_br_query_Form", "图书序号："))
        self.query_bn.setText(_translate("r_br_query_Form", "搜索"))
        self.all_rb.setText(_translate("r_br_query_Form", "查询全部记录"))
        self.notre_rb.setText(_translate("r_br_query_Form", "查询未还记录"))
        self.q_all_btn.setText(_translate("r_br_query_Form", "一键查询全部未还图书"))

class Ui_r_insert_Form(object):
    def setupUi(self, r_insert_Form):
        r_insert_Form.setObjectName("r_insert_Form")
        r_insert_Form.resize(410, 367)
        self.gridLayout_2 = QtWidgets.QGridLayout(r_insert_Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_18 = QtWidgets.QLabel(r_insert_Form)
        self.label_18.setFrameShape(QtWidgets.QFrame.Box)
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap(":/Icon/load.png"))
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_4.addWidget(self.label_18)
        self.load_photo_btn = QtWidgets.QPushButton(r_insert_Form)
        self.load_photo_btn.setEnabled(True)
        self.load_photo_btn.setAutoFillBackground(False)
        self.load_photo_btn.setAutoRepeat(False)
        self.load_photo_btn.setObjectName("load_photo_btn")
        self.verticalLayout_4.addWidget(self.load_photo_btn)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_6 = QtWidgets.QLabel(r_insert_Form)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(r_insert_Form)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(r_insert_Form)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.label_11 = QtWidgets.QLabel(r_insert_Form)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.label_9 = QtWidgets.QLabel(r_insert_Form)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(r_insert_Form)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.label_12 = QtWidgets.QLabel(r_insert_Form)
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(r_insert_Form)
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(r_insert_Form)
        self.label_14.setObjectName("label_14")
        self.verticalLayout.addWidget(self.label_14)
        self.label_15 = QtWidgets.QLabel(r_insert_Form)
        self.label_15.setObjectName("label_15")
        self.verticalLayout.addWidget(self.label_15)
        self.label_17 = QtWidgets.QLabel(r_insert_Form)
        self.label_17.setObjectName("label_17")
        self.verticalLayout.addWidget(self.label_17)
        self.label_16 = QtWidgets.QLabel(r_insert_Form)
        self.label_16.setObjectName("label_16")
        self.verticalLayout.addWidget(self.label_16)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.id_le = QtWidgets.QLineEdit(r_insert_Form)
        self.id_le.setObjectName("id_le")
        self.verticalLayout_2.addWidget(self.id_le)
        self.name_le = QtWidgets.QLineEdit(r_insert_Form)
        self.name_le.setObjectName("name_le")
        self.verticalLayout_2.addWidget(self.name_le)
        self.sex_cb = QtWidgets.QComboBox(r_insert_Form)
        self.sex_cb.setObjectName("sex_cb")
        self.sex_cb.addItem("")
        self.sex_cb.addItem("")
        self.verticalLayout_2.addWidget(self.sex_cb)
        self.type_cb = QtWidgets.QComboBox(r_insert_Form)
        self.type_cb.setObjectName("type_cb")
        self.type_cb.addItem("")
        self.type_cb.addItem("")
        self.type_cb.addItem("")
        self.type_cb.addItem("")
        self.type_cb.addItem("")
        self.verticalLayout_2.addWidget(self.type_cb)
        self.dept_le = QtWidgets.QLineEdit(r_insert_Form)
        self.dept_le.setObjectName("dept_le")
        self.verticalLayout_2.addWidget(self.dept_le)
        self.phone_le = QtWidgets.QLineEdit(r_insert_Form)
        self.phone_le.setObjectName("phone_le")
        self.verticalLayout_2.addWidget(self.phone_le)
        self.email_le = QtWidgets.QLineEdit(r_insert_Form)
        self.email_le.setObjectName("email_le")
        self.verticalLayout_2.addWidget(self.email_le)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.date_le = QtWidgets.QLineEdit(r_insert_Form)
        self.date_le.setEnabled(False)
        self.date_le.setObjectName("date_le")
        self.horizontalLayout_3.addWidget(self.date_le)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.status_le = QtWidgets.QLineEdit(r_insert_Form)
        self.status_le.setEnabled(False)
        self.status_le.setObjectName("status_le")
        self.verticalLayout_2.addWidget(self.status_le)
        self.bwqty_le = QtWidgets.QLineEdit(r_insert_Form)
        self.bwqty_le.setEnabled(False)
        self.bwqty_le.setObjectName("bwqty_le")
        self.verticalLayout_2.addWidget(self.bwqty_le)
        self.psw_le = QtWidgets.QLineEdit(r_insert_Form)
        self.psw_le.setEchoMode(QtWidgets.QLineEdit.Password)
        self.psw_le.setObjectName("psw_le")
        self.verticalLayout_2.addWidget(self.psw_le)
        self.roles_cb = QtWidgets.QComboBox(r_insert_Form)
        self.roles_cb.setObjectName("roles_cb")
        self.roles_cb.addItem("")
        self.roles_cb.addItem("")
        self.roles_cb.addItem("")
        self.roles_cb.addItem("")
        self.roles_cb.addItem("")
        self.verticalLayout_2.addWidget(self.roles_cb)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.insert_btn = QtWidgets.QPushButton(r_insert_Form)
        self.insert_btn.setEnabled(True)
        self.insert_btn.setAutoFillBackground(False)
        self.insert_btn.setAutoRepeat(False)
        self.insert_btn.setObjectName("insert_btn")
        self.verticalLayout_5.addWidget(self.insert_btn)
        self.gridLayout.addLayout(self.verticalLayout_5, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(r_insert_Form)
        self.type_cb.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(r_insert_Form)

    def retranslateUi(self, r_insert_Form):
        _translate = QtCore.QCoreApplication.translate
        r_insert_Form.setWindowTitle(_translate("r_insert_Form", "添加"))
        self.load_photo_btn.setText(_translate("r_insert_Form", "载入照片"))
        self.label_6.setText(_translate("r_insert_Form", "编号："))
        self.label_7.setText(_translate("r_insert_Form", "姓名："))
        self.label_8.setText(_translate("r_insert_Form", "性别："))
        self.label_11.setText(_translate("r_insert_Form", "类别："))
        self.label_9.setText(_translate("r_insert_Form", "单位名称："))
        self.label_10.setText(_translate("r_insert_Form", "电话号码："))
        self.label_12.setText(_translate("r_insert_Form", "电子邮箱："))
        self.label_13.setText(_translate("r_insert_Form", "登记日期："))
        self.label_14.setText(_translate("r_insert_Form", "证件状态："))
        self.label_15.setText(_translate("r_insert_Form", "已借数量："))
        self.label_17.setText(_translate("r_insert_Form", "登陆密码："))
        self.label_16.setText(_translate("r_insert_Form", "管理角色："))
        self.sex_cb.setItemText(0, _translate("r_insert_Form", "男"))
        self.sex_cb.setItemText(1, _translate("r_insert_Form", "女"))
        self.type_cb.setItemText(0, _translate("r_insert_Form", "老师"))
        self.type_cb.setItemText(1, _translate("r_insert_Form", "博士生"))
        self.type_cb.setItemText(2, _translate("r_insert_Form", "硕士生"))
        self.type_cb.setItemText(3, _translate("r_insert_Form", "本科生"))
        self.type_cb.setItemText(4, _translate("r_insert_Form", "专科生"))
        self.date_le.setText(_translate("r_insert_Form", "设置为当前时间"))
        self.status_le.setText(_translate("r_insert_Form", "有效"))
        self.bwqty_le.setText(_translate("r_insert_Form", "初始值为0"))
        self.psw_le.setPlaceholderText(_translate("r_insert_Form", "无输入则初始密码为123"))
        self.roles_cb.setItemText(0, _translate("r_insert_Form", "读者"))
        self.roles_cb.setItemText(1, _translate("r_insert_Form", "借书证管理员"))
        self.roles_cb.setItemText(2, _translate("r_insert_Form", "图书管理员"))
        self.roles_cb.setItemText(3, _translate("r_insert_Form", "借阅管理员"))
        self.roles_cb.setItemText(4, _translate("r_insert_Form", "系统管理员"))
        self.insert_btn.setText(_translate("r_insert_Form", "确认添加"))

class Ui_b_insert_Form(object):
    def setupUi(self, b_insert_Form):
        b_insert_Form.setObjectName("b_insert_Form")
        b_insert_Form.resize(410, 389)
        self.gridLayout = QtWidgets.QGridLayout(b_insert_Form)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_18 = QtWidgets.QLabel(b_insert_Form)
        self.label_18.setFrameShape(QtWidgets.QFrame.Box)
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap(":/Icon/book.png"))
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_4.addWidget(self.label_18)
        self.load_photo_btn = QtWidgets.QPushButton(b_insert_Form)
        self.load_photo_btn.setEnabled(True)
        self.load_photo_btn.setAutoFillBackground(False)
        self.load_photo_btn.setAutoRepeat(False)
        self.load_photo_btn.setObjectName("load_photo_btn")
        self.verticalLayout_4.addWidget(self.load_photo_btn)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_6 = QtWidgets.QLabel(b_insert_Form)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(b_insert_Form)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(b_insert_Form)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.label_11 = QtWidgets.QLabel(b_insert_Form)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.label_9 = QtWidgets.QLabel(b_insert_Form)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(b_insert_Form)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.label_12 = QtWidgets.QLabel(b_insert_Form)
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(b_insert_Form)
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(b_insert_Form)
        self.label_14.setObjectName("label_14")
        self.verticalLayout.addWidget(self.label_14)
        self.label_15 = QtWidgets.QLabel(b_insert_Form)
        self.label_15.setObjectName("label_15")
        self.verticalLayout.addWidget(self.label_15)
        self.label_17 = QtWidgets.QLabel(b_insert_Form)
        self.label_17.setObjectName("label_17")
        self.verticalLayout.addWidget(self.label_17)
        self.label_16 = QtWidgets.QLabel(b_insert_Form)
        self.label_16.setObjectName("label_16")
        self.verticalLayout.addWidget(self.label_16)
        self.label_19 = QtWidgets.QLabel(b_insert_Form)
        self.label_19.setObjectName("label_19")
        self.verticalLayout.addWidget(self.label_19)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.id_le = QtWidgets.QLineEdit(b_insert_Form)
        self.id_le.setEnabled(False)
        self.id_le.setObjectName("id_le")
        self.verticalLayout_2.addWidget(self.id_le)
        self.code_le = QtWidgets.QLineEdit(b_insert_Form)
        self.code_le.setObjectName("code_le")
        self.verticalLayout_2.addWidget(self.code_le)
        self.name_le = QtWidgets.QLineEdit(b_insert_Form)
        self.name_le.setObjectName("name_le")
        self.verticalLayout_2.addWidget(self.name_le)
        self.author_le = QtWidgets.QLineEdit(b_insert_Form)
        self.author_le.setObjectName("author_le")
        self.verticalLayout_2.addWidget(self.author_le)
        self.press_le = QtWidgets.QLineEdit(b_insert_Form)
        self.press_le.setObjectName("press_le")
        self.verticalLayout_2.addWidget(self.press_le)
        self.datepress_le = QtWidgets.QLineEdit(b_insert_Form)
        self.datepress_le.setObjectName("datepress_le")
        self.verticalLayout_2.addWidget(self.datepress_le)
        self.ISBN_le = QtWidgets.QLineEdit(b_insert_Form)
        self.ISBN_le.setObjectName("ISBN_le")
        self.verticalLayout_2.addWidget(self.ISBN_le)
        self.language_cb = QtWidgets.QComboBox(b_insert_Form)
        self.language_cb.setObjectName("language_cb")
        self.language_cb.addItem("")
        self.language_cb.addItem("")
        self.language_cb.addItem("")
        self.language_cb.addItem("")
        self.language_cb.addItem("")
        self.language_cb.addItem("")
        self.verticalLayout_2.addWidget(self.language_cb)
        self.pages_le = QtWidgets.QLineEdit(b_insert_Form)
        self.pages_le.setObjectName("pages_le")
        self.verticalLayout_2.addWidget(self.pages_le)
        self.price_le = QtWidgets.QLineEdit(b_insert_Form)
        self.price_le.setObjectName("price_le")
        self.verticalLayout_2.addWidget(self.price_le)
        self.dateln_le = QtWidgets.QLineEdit(b_insert_Form)
        self.dateln_le.setEnabled(False)
        self.dateln_le.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.dateln_le.setObjectName("dateln_le")
        self.verticalLayout_2.addWidget(self.dateln_le)
        self.brief_le = QtWidgets.QLineEdit(b_insert_Form)
        self.brief_le.setObjectName("brief_le")
        self.verticalLayout_2.addWidget(self.brief_le)
        self.status_cb = QtWidgets.QComboBox(b_insert_Form)
        self.status_cb.setObjectName("status_cb")
        self.status_cb.addItem("")
        self.status_cb.addItem("")
        self.status_cb.addItem("")
        self.status_cb.addItem("")
        self.status_cb.addItem("")
        self.verticalLayout_2.addWidget(self.status_cb)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.insert_btn = QtWidgets.QPushButton(b_insert_Form)
        self.insert_btn.setEnabled(True)
        self.insert_btn.setAutoFillBackground(False)
        self.insert_btn.setAutoRepeat(False)
        self.insert_btn.setObjectName("insert_btn")
        self.verticalLayout_5.addWidget(self.insert_btn)
        self.gridLayout.addLayout(self.verticalLayout_5, 0, 0, 1, 1)

        self.retranslateUi(b_insert_Form)
        QtCore.QMetaObject.connectSlotsByName(b_insert_Form)

    def retranslateUi(self, b_insert_Form):
        _translate = QtCore.QCoreApplication.translate
        b_insert_Form.setWindowTitle(_translate("b_insert_Form", "添加图书"))
        self.load_photo_btn.setText(_translate("b_insert_Form", "载入书籍封面"))
        self.label_6.setText(_translate("b_insert_Form", "序号："))
        self.label_7.setText(_translate("b_insert_Form", "编号："))
        self.label_8.setText(_translate("b_insert_Form", "书名："))
        self.label_11.setText(_translate("b_insert_Form", "作者："))
        self.label_9.setText(_translate("b_insert_Form", "出版社："))
        self.label_10.setText(_translate("b_insert_Form", "出版日期："))
        self.label_12.setText(_translate("b_insert_Form", "ISBN书号："))
        self.label_13.setText(_translate("b_insert_Form", "语言："))
        self.label_14.setText(_translate("b_insert_Form", "页数："))
        self.label_15.setText(_translate("b_insert_Form", "价格："))
        self.label_17.setText(_translate("b_insert_Form", "入馆日期："))
        self.label_16.setText(_translate("b_insert_Form", "内容简介："))
        self.label_19.setText(_translate("b_insert_Form", "图书状态："))
        self.datepress_le.setPlaceholderText(_translate("b_insert_Form", "格式：yy-mm-dd"))
        self.language_cb.setItemText(0, _translate("b_insert_Form", "中文"))
        self.language_cb.setItemText(1, _translate("b_insert_Form", "英文"))
        self.language_cb.setItemText(2, _translate("b_insert_Form", "日文"))
        self.language_cb.setItemText(3, _translate("b_insert_Form", "俄文"))
        self.language_cb.setItemText(4, _translate("b_insert_Form", "德文"))
        self.language_cb.setItemText(5, _translate("b_insert_Form", "法文"))
        self.dateln_le.setText(_translate("b_insert_Form", "自动设置为当前时间"))
        self.status_cb.setItemText(0, _translate("b_insert_Form", "在馆"))
        self.status_cb.setItemText(1, _translate("b_insert_Form", "借出"))
        self.status_cb.setItemText(2, _translate("b_insert_Form", "遗失"))
        self.status_cb.setItemText(3, _translate("b_insert_Form", "变卖"))
        self.status_cb.setItemText(4, _translate("b_insert_Form", "销毁"))
        self.insert_btn.setText(_translate("b_insert_Form", "确认添加"))

class Ui_r_ud_Form(object):
    def setupUi(self, r_ud_Form):
        r_ud_Form.setObjectName("r_ud_Form")
        r_ud_Form.resize(410, 369)
        self.gridLayout_2 = QtWidgets.QGridLayout(r_ud_Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_18 = QtWidgets.QLabel(r_ud_Form)
        self.label_18.setFrameShape(QtWidgets.QFrame.Box)
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap(":/Icon/load.png"))
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_4.addWidget(self.label_18)
        self.load_photo_btn = QtWidgets.QPushButton(r_ud_Form)
        self.load_photo_btn.setEnabled(True)
        self.load_photo_btn.setAutoFillBackground(False)
        self.load_photo_btn.setAutoRepeat(False)
        self.load_photo_btn.setObjectName("load_photo_btn")
        self.verticalLayout_4.addWidget(self.load_photo_btn)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_6 = QtWidgets.QLabel(r_ud_Form)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(r_ud_Form)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(r_ud_Form)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.label_11 = QtWidgets.QLabel(r_ud_Form)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.label_9 = QtWidgets.QLabel(r_ud_Form)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(r_ud_Form)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.label_12 = QtWidgets.QLabel(r_ud_Form)
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(r_ud_Form)
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(r_ud_Form)
        self.label_14.setObjectName("label_14")
        self.verticalLayout.addWidget(self.label_14)
        self.label_15 = QtWidgets.QLabel(r_ud_Form)
        self.label_15.setObjectName("label_15")
        self.verticalLayout.addWidget(self.label_15)
        self.label_17 = QtWidgets.QLabel(r_ud_Form)
        self.label_17.setObjectName("label_17")
        self.verticalLayout.addWidget(self.label_17)
        self.label_16 = QtWidgets.QLabel(r_ud_Form)
        self.label_16.setObjectName("label_16")
        self.verticalLayout.addWidget(self.label_16)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.id_le = QtWidgets.QLineEdit(r_ud_Form)
        self.id_le.setEnabled(False)
        self.id_le.setObjectName("id_le")
        self.verticalLayout_2.addWidget(self.id_le)
        self.name_le = QtWidgets.QLineEdit(r_ud_Form)
        self.name_le.setObjectName("name_le")
        self.verticalLayout_2.addWidget(self.name_le)
        self.sex_cb = QtWidgets.QComboBox(r_ud_Form)
        self.sex_cb.setObjectName("sex_cb")
        self.sex_cb.addItem("")
        self.sex_cb.addItem("")
        self.verticalLayout_2.addWidget(self.sex_cb)
        self.type_cb = QtWidgets.QComboBox(r_ud_Form)
        self.type_cb.setObjectName("type_cb")
        self.type_cb.addItem("")
        self.type_cb.addItem("")
        self.type_cb.addItem("")
        self.type_cb.addItem("")
        self.type_cb.addItem("")
        self.verticalLayout_2.addWidget(self.type_cb)
        self.dept_le = QtWidgets.QLineEdit(r_ud_Form)
        self.dept_le.setObjectName("dept_le")
        self.verticalLayout_2.addWidget(self.dept_le)
        self.phone_le = QtWidgets.QLineEdit(r_ud_Form)
        self.phone_le.setObjectName("phone_le")
        self.verticalLayout_2.addWidget(self.phone_le)
        self.email_le = QtWidgets.QLineEdit(r_ud_Form)
        self.email_le.setObjectName("email_le")
        self.verticalLayout_2.addWidget(self.email_le)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.date_le = QtWidgets.QLineEdit(r_ud_Form)
        self.date_le.setEnabled(False)
        self.date_le.setObjectName("date_le")
        self.horizontalLayout_3.addWidget(self.date_le)
        self.date_cb = QtWidgets.QCheckBox(r_ud_Form)
        self.date_cb.setCheckable(True)
        self.date_cb.setObjectName("date_cb")
        self.horizontalLayout_3.addWidget(self.date_cb)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.status_cb = QtWidgets.QComboBox(r_ud_Form)
        self.status_cb.setObjectName("status_cb")
        self.status_cb.addItem("")
        self.status_cb.addItem("")
        self.status_cb.addItem("")
        self.verticalLayout_2.addWidget(self.status_cb)
        self.bwqty_le = QtWidgets.QLineEdit(r_ud_Form)
        self.bwqty_le.setEnabled(False)
        self.bwqty_le.setObjectName("bwqty_le")
        self.verticalLayout_2.addWidget(self.bwqty_le)
        self.psw_le = QtWidgets.QLineEdit(r_ud_Form)
        self.psw_le.setEchoMode(QtWidgets.QLineEdit.Password)
        self.psw_le.setObjectName("psw_le")
        self.verticalLayout_2.addWidget(self.psw_le)
        self.roles_cb = QtWidgets.QComboBox(r_ud_Form)
        self.roles_cb.setObjectName("roles_cb")
        self.roles_cb.addItem("")
        self.roles_cb.addItem("")
        self.roles_cb.addItem("")
        self.roles_cb.addItem("")
        self.roles_cb.addItem("")
        self.verticalLayout_2.addWidget(self.roles_cb)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.update_btn = QtWidgets.QPushButton(r_ud_Form)
        self.update_btn.setObjectName("update_btn")
        self.horizontalLayout_4.addWidget(self.update_btn)
        self.delete_btn = QtWidgets.QPushButton(r_ud_Form)
        self.delete_btn.setObjectName("delete_btn")
        self.horizontalLayout_4.addWidget(self.delete_btn)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.gridLayout.addLayout(self.verticalLayout_5, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(r_ud_Form)
        self.type_cb.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(r_ud_Form)

    def retranslateUi(self, r_ud_Form):
        _translate = QtCore.QCoreApplication.translate
        r_ud_Form.setWindowTitle(_translate("r_ud_Form", "详情"))
        self.load_photo_btn.setText(_translate("r_ud_Form", "载入照片"))
        self.label_6.setText(_translate("r_ud_Form", "编号："))
        self.label_7.setText(_translate("r_ud_Form", "姓名："))
        self.label_8.setText(_translate("r_ud_Form", "性别："))
        self.label_11.setText(_translate("r_ud_Form", "类别："))
        self.label_9.setText(_translate("r_ud_Form", "单位名称："))
        self.label_10.setText(_translate("r_ud_Form", "电话号码："))
        self.label_12.setText(_translate("r_ud_Form", "电子邮箱："))
        self.label_13.setText(_translate("r_ud_Form", "登记日期："))
        self.label_14.setText(_translate("r_ud_Form", "证件状态："))
        self.label_15.setText(_translate("r_ud_Form", "已借数量："))
        self.label_17.setText(_translate("r_ud_Form", "登陆密码："))
        self.label_16.setText(_translate("r_ud_Form", "管理角色："))
        self.sex_cb.setItemText(0, _translate("r_ud_Form", "男"))
        self.sex_cb.setItemText(1, _translate("r_ud_Form", "女"))
        self.type_cb.setItemText(0, _translate("r_ud_Form", "老师"))
        self.type_cb.setItemText(1, _translate("r_ud_Form", "博士生"))
        self.type_cb.setItemText(2, _translate("r_ud_Form", "硕士生"))
        self.type_cb.setItemText(3, _translate("r_ud_Form", "本科生"))
        self.type_cb.setItemText(4, _translate("r_ud_Form", "专科生"))
        self.date_le.setText(_translate("r_ud_Form", "更新为当前时间"))
        self.date_cb.setText(_translate("r_ud_Form", "更新"))
        self.status_cb.setItemText(0, _translate("r_ud_Form", "有效"))
        self.status_cb.setItemText(1, _translate("r_ud_Form", "挂失"))
        self.status_cb.setItemText(2, _translate("r_ud_Form", "注销"))
        self.roles_cb.setItemText(0, _translate("r_ud_Form", "读者"))
        self.roles_cb.setItemText(1, _translate("r_ud_Form", "借书证管理员"))
        self.roles_cb.setItemText(2, _translate("r_ud_Form", "图书管理员"))
        self.roles_cb.setItemText(3, _translate("r_ud_Form", "借阅管理员"))
        self.roles_cb.setItemText(4, _translate("r_ud_Form", "系统管理员"))
        self.update_btn.setText(_translate("r_ud_Form", "更新信息"))
        self.delete_btn.setText(_translate("r_ud_Form", "删除用户"))

class Ui_b_ud_Form(object):
    def setupUi(self, b_ud_Form):
        b_ud_Form.setObjectName("b_ud_Form")
        b_ud_Form.resize(450, 422)
        self.gridLayout = QtWidgets.QGridLayout(b_ud_Form)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_18 = QtWidgets.QLabel(b_ud_Form)
        self.label_18.setFrameShape(QtWidgets.QFrame.Box)
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap(":/Icon/book.png"))
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_4.addWidget(self.label_18)
        self.load_photo_btn = QtWidgets.QPushButton(b_ud_Form)
        self.load_photo_btn.setEnabled(True)
        self.load_photo_btn.setAutoFillBackground(False)
        self.load_photo_btn.setAutoRepeat(False)
        self.load_photo_btn.setObjectName("load_photo_btn")
        self.verticalLayout_4.addWidget(self.load_photo_btn)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_6 = QtWidgets.QLabel(b_ud_Form)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(b_ud_Form)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(b_ud_Form)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.label_11 = QtWidgets.QLabel(b_ud_Form)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.label_9 = QtWidgets.QLabel(b_ud_Form)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(b_ud_Form)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.label_12 = QtWidgets.QLabel(b_ud_Form)
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(b_ud_Form)
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(b_ud_Form)
        self.label_14.setObjectName("label_14")
        self.verticalLayout.addWidget(self.label_14)
        self.label_15 = QtWidgets.QLabel(b_ud_Form)
        self.label_15.setObjectName("label_15")
        self.verticalLayout.addWidget(self.label_15)
        self.label_17 = QtWidgets.QLabel(b_ud_Form)
        self.label_17.setObjectName("label_17")
        self.verticalLayout.addWidget(self.label_17)
        self.label_16 = QtWidgets.QLabel(b_ud_Form)
        self.label_16.setObjectName("label_16")
        self.verticalLayout.addWidget(self.label_16)
        self.label_19 = QtWidgets.QLabel(b_ud_Form)
        self.label_19.setObjectName("label_19")
        self.verticalLayout.addWidget(self.label_19)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.id_le = QtWidgets.QLineEdit(b_ud_Form)
        self.id_le.setEnabled(False)
        self.id_le.setObjectName("id_le")
        self.verticalLayout_2.addWidget(self.id_le)
        self.code_le = QtWidgets.QLineEdit(b_ud_Form)
        self.code_le.setObjectName("code_le")
        self.verticalLayout_2.addWidget(self.code_le)
        self.name_le = QtWidgets.QLineEdit(b_ud_Form)
        self.name_le.setObjectName("name_le")
        self.verticalLayout_2.addWidget(self.name_le)
        self.author_le = QtWidgets.QLineEdit(b_ud_Form)
        self.author_le.setObjectName("author_le")
        self.verticalLayout_2.addWidget(self.author_le)
        self.press_le = QtWidgets.QLineEdit(b_ud_Form)
        self.press_le.setObjectName("press_le")
        self.verticalLayout_2.addWidget(self.press_le)
        self.datepress_le = QtWidgets.QLineEdit(b_ud_Form)
        self.datepress_le.setObjectName("datepress_le")
        self.verticalLayout_2.addWidget(self.datepress_le)
        self.ISBN_le = QtWidgets.QLineEdit(b_ud_Form)
        self.ISBN_le.setObjectName("ISBN_le")
        self.verticalLayout_2.addWidget(self.ISBN_le)
        self.language_cb = QtWidgets.QComboBox(b_ud_Form)
        self.language_cb.setObjectName("language_cb")
        self.language_cb.addItem("")
        self.language_cb.addItem("")
        self.language_cb.addItem("")
        self.language_cb.addItem("")
        self.language_cb.addItem("")
        self.language_cb.addItem("")
        self.verticalLayout_2.addWidget(self.language_cb)
        self.pages_le = QtWidgets.QLineEdit(b_ud_Form)
        self.pages_le.setObjectName("pages_le")
        self.verticalLayout_2.addWidget(self.pages_le)
        self.price_le = QtWidgets.QLineEdit(b_ud_Form)
        self.price_le.setObjectName("price_le")
        self.verticalLayout_2.addWidget(self.price_le)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.dateln_le = QtWidgets.QLineEdit(b_ud_Form)
        self.dateln_le.setEnabled(False)
        self.dateln_le.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.dateln_le.setObjectName("dateln_le")
        self.horizontalLayout_3.addWidget(self.dateln_le)
        self.dateln_cb = QtWidgets.QCheckBox(b_ud_Form)
        self.dateln_cb.setObjectName("dateln_cb")
        self.horizontalLayout_3.addWidget(self.dateln_cb)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.brief_le = QtWidgets.QLineEdit(b_ud_Form)
        self.brief_le.setObjectName("brief_le")
        self.verticalLayout_2.addWidget(self.brief_le)
        self.status_cb = QtWidgets.QComboBox(b_ud_Form)
        self.status_cb.setObjectName("status_cb")
        self.status_cb.addItem("")
        self.status_cb.addItem("")
        self.status_cb.addItem("")
        self.status_cb.addItem("")
        self.status_cb.addItem("")
        self.verticalLayout_2.addWidget(self.status_cb)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.update_btn = QtWidgets.QPushButton(b_ud_Form)
        self.update_btn.setObjectName("update_btn")
        self.horizontalLayout_4.addWidget(self.update_btn)
        self.delete_btn = QtWidgets.QPushButton(b_ud_Form)
        self.delete_btn.setObjectName("delete_btn")
        self.horizontalLayout_4.addWidget(self.delete_btn)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.sst_btn = QtWidgets.QPushButton(b_ud_Form)
        self.sst_btn.setObjectName("sst_btn")
        self.verticalLayout_5.addWidget(self.sst_btn)
        self.gridLayout.addLayout(self.verticalLayout_5, 0, 0, 1, 1)

        self.retranslateUi(b_ud_Form)
        QtCore.QMetaObject.connectSlotsByName(b_ud_Form)

    def retranslateUi(self, b_ud_Form):
        _translate = QtCore.QCoreApplication.translate
        b_ud_Form.setWindowTitle(_translate("b_ud_Form", "详情"))
        self.load_photo_btn.setText(_translate("b_ud_Form", "载入书籍封面"))
        self.label_6.setText(_translate("b_ud_Form", "序号："))
        self.label_7.setText(_translate("b_ud_Form", "编号："))
        self.label_8.setText(_translate("b_ud_Form", "书名："))
        self.label_11.setText(_translate("b_ud_Form", "作者："))
        self.label_9.setText(_translate("b_ud_Form", "出版社："))
        self.label_10.setText(_translate("b_ud_Form", "出版日期："))
        self.label_12.setText(_translate("b_ud_Form", "ISBN书号："))
        self.label_13.setText(_translate("b_ud_Form", "语言："))
        self.label_14.setText(_translate("b_ud_Form", "页数："))
        self.label_15.setText(_translate("b_ud_Form", "价格："))
        self.label_17.setText(_translate("b_ud_Form", "入馆日期："))
        self.label_16.setText(_translate("b_ud_Form", "内容简介："))
        self.label_19.setText(_translate("b_ud_Form", "图书状态："))
        self.datepress_le.setPlaceholderText(_translate("b_ud_Form", "格式：yy-mm-dd"))
        self.language_cb.setItemText(0, _translate("b_ud_Form", "中文"))
        self.language_cb.setItemText(1, _translate("b_ud_Form", "英文"))
        self.language_cb.setItemText(2, _translate("b_ud_Form", "日文"))
        self.language_cb.setItemText(3, _translate("b_ud_Form", "俄文"))
        self.language_cb.setItemText(4, _translate("b_ud_Form", "德文"))
        self.language_cb.setItemText(5, _translate("b_ud_Form", "法文"))
        self.dateln_le.setText(_translate("b_ud_Form", "更新为当前时间"))
        self.dateln_cb.setText(_translate("b_ud_Form", "更新"))
        self.status_cb.setItemText(0, _translate("b_ud_Form", "在馆"))
        self.status_cb.setItemText(1, _translate("b_ud_Form", "借出"))
        self.status_cb.setItemText(2, _translate("b_ud_Form", "遗失"))
        self.status_cb.setItemText(3, _translate("b_ud_Form", "变卖"))
        self.status_cb.setItemText(4, _translate("b_ud_Form", "销毁"))
        self.update_btn.setText(_translate("b_ud_Form", "更新信息"))
        self.delete_btn.setText(_translate("b_ud_Form", "删除图书"))
        self.sst_btn.setText(_translate("b_ud_Form", "预约借书"))

class Ui_br_book_Form(object):
    def setupUi(self, br_book_Form):
        br_book_Form.setObjectName("br_book_Form")
        br_book_Form.resize(250, 151)
        self.gridLayout = QtWidgets.QGridLayout(br_book_Form)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.br_id_label = QtWidgets.QLabel(br_book_Form)
        self.br_id_label.setObjectName("br_id_label")
        self.verticalLayout.addWidget(self.br_id_label)
        self.r_id_label = QtWidgets.QLabel(br_book_Form)
        self.r_id_label.setObjectName("r_id_label")
        self.verticalLayout.addWidget(self.r_id_label)
        self.b_id_label = QtWidgets.QLabel(br_book_Form)
        self.b_id_label.setObjectName("b_id_label")
        self.verticalLayout.addWidget(self.b_id_label)
        self.a_id_label = QtWidgets.QLabel(br_book_Form)
        self.a_id_label.setObjectName("a_id_label")
        self.verticalLayout.addWidget(self.a_id_label)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.br_id_le = QtWidgets.QLineEdit(br_book_Form)
        self.br_id_le.setEnabled(False)
        self.br_id_le.setObjectName("br_id_le")
        self.verticalLayout_2.addWidget(self.br_id_le)
        self.r_id_le = QtWidgets.QLineEdit(br_book_Form)
        self.r_id_le.setObjectName("r_id_le")
        self.verticalLayout_2.addWidget(self.r_id_le)
        self.b_id_le = QtWidgets.QLineEdit(br_book_Form)
        self.b_id_le.setObjectName("b_id_le")
        self.verticalLayout_2.addWidget(self.b_id_le)
        self.a_id_le = QtWidgets.QLineEdit(br_book_Form)
        self.a_id_le.setEnabled(False)
        self.a_id_le.setObjectName("a_id_le")
        self.verticalLayout_2.addWidget(self.a_id_le)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.br_book_btn = QtWidgets.QPushButton(br_book_Form)
        self.br_book_btn.setObjectName("br_book_btn")
        self.verticalLayout_3.addWidget(self.br_book_btn)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 1)

        self.retranslateUi(br_book_Form)
        QtCore.QMetaObject.connectSlotsByName(br_book_Form)

    def retranslateUi(self, br_book_Form):
        _translate = QtCore.QCoreApplication.translate
        br_book_Form.setWindowTitle(_translate("br_book_Form", "借书"))
        self.br_id_label.setText(_translate("br_book_Form", "借书序号："))
        self.r_id_label.setText(_translate("br_book_Form", "读者编号："))
        self.b_id_label.setText(_translate("br_book_Form", "图书序号："))
        self.a_id_label.setText(_translate("br_book_Form", "借书操作员："))
        self.br_book_btn.setText(_translate("br_book_Form", "确认借书"))
