# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'b_ud.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_b_ud_Form(object):
    def setupUi(self, b_ud_Form):
        b_ud_Form.setObjectName("b_ud_Form")
        b_ud_Form.resize(450, 422)
        self.gridLayout = QtWidgets.QGridLayout(b_ud_Form)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_18 = QtWidgets.QLabel(b_ud_Form)
        self.label_18.setFrameShape(QtWidgets.QFrame.Box)
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap(":/Icon/book.png"))
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_4.addWidget(self.label_18)
        self.load_photo_btn = QtWidgets.QPushButton(b_ud_Form)
        self.load_photo_btn.setEnabled(True)
        self.load_photo_btn.setAutoFillBackground(False)
        self.load_photo_btn.setAutoRepeat(False)
        self.load_photo_btn.setObjectName("load_photo_btn")
        self.verticalLayout_4.addWidget(self.load_photo_btn)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_6 = QtWidgets.QLabel(b_ud_Form)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(b_ud_Form)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(b_ud_Form)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.label_11 = QtWidgets.QLabel(b_ud_Form)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.label_9 = QtWidgets.QLabel(b_ud_Form)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(b_ud_Form)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.label_12 = QtWidgets.QLabel(b_ud_Form)
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(b_ud_Form)
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(b_ud_Form)
        self.label_14.setObjectName("label_14")
        self.verticalLayout.addWidget(self.label_14)
        self.label_15 = QtWidgets.QLabel(b_ud_Form)
        self.label_15.setObjectName("label_15")
        self.verticalLayout.addWidget(self.label_15)
        self.label_17 = QtWidgets.QLabel(b_ud_Form)
        self.label_17.setObjectName("label_17")
        self.verticalLayout.addWidget(self.label_17)
        self.label_16 = QtWidgets.QLabel(b_ud_Form)
        self.label_16.setObjectName("label_16")
        self.verticalLayout.addWidget(self.label_16)
        self.label_19 = QtWidgets.QLabel(b_ud_Form)
        self.label_19.setObjectName("label_19")
        self.verticalLayout.addWidget(self.label_19)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.id_le = QtWidgets.QLineEdit(b_ud_Form)
        self.id_le.setEnabled(False)
        self.id_le.setObjectName("id_le")
        self.verticalLayout_2.addWidget(self.id_le)
        self.code_le = QtWidgets.QLineEdit(b_ud_Form)
        self.code_le.setObjectName("code_le")
        self.verticalLayout_2.addWidget(self.code_le)
        self.name_le = QtWidgets.QLineEdit(b_ud_Form)
        self.name_le.setObjectName("name_le")
        self.verticalLayout_2.addWidget(self.name_le)
        self.author_le = QtWidgets.QLineEdit(b_ud_Form)
        self.author_le.setObjectName("author_le")
        self.verticalLayout_2.addWidget(self.author_le)
        self.press_le = QtWidgets.QLineEdit(b_ud_Form)
        self.press_le.setObjectName("press_le")
        self.verticalLayout_2.addWidget(self.press_le)
        self.datepress_le = QtWidgets.QLineEdit(b_ud_Form)
        self.datepress_le.setObjectName("datepress_le")
        self.verticalLayout_2.addWidget(self.datepress_le)
        self.ISBN_le = QtWidgets.QLineEdit(b_ud_Form)
        self.ISBN_le.setObjectName("ISBN_le")
        self.verticalLayout_2.addWidget(self.ISBN_le)
        self.language_cb = QtWidgets.QComboBox(b_ud_Form)
        self.language_cb.setObjectName("language_cb")
        self.language_cb.addItem("")
        self.language_cb.addItem("")
        self.language_cb.addItem("")
        self.language_cb.addItem("")
        self.language_cb.addItem("")
        self.language_cb.addItem("")
        self.verticalLayout_2.addWidget(self.language_cb)
        self.pages_le = QtWidgets.QLineEdit(b_ud_Form)
        self.pages_le.setObjectName("pages_le")
        self.verticalLayout_2.addWidget(self.pages_le)
        self.price_le = QtWidgets.QLineEdit(b_ud_Form)
        self.price_le.setObjectName("price_le")
        self.verticalLayout_2.addWidget(self.price_le)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.dateln_le = QtWidgets.QLineEdit(b_ud_Form)
        self.dateln_le.setEnabled(False)
        self.dateln_le.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.dateln_le.setObjectName("dateln_le")
        self.horizontalLayout_3.addWidget(self.dateln_le)
        self.dateln_cb = QtWidgets.QCheckBox(b_ud_Form)
        self.dateln_cb.setObjectName("dateln_cb")
        self.horizontalLayout_3.addWidget(self.dateln_cb)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.brief_le = QtWidgets.QLineEdit(b_ud_Form)
        self.brief_le.setObjectName("brief_le")
        self.verticalLayout_2.addWidget(self.brief_le)
        self.status_cb = QtWidgets.QComboBox(b_ud_Form)
        self.status_cb.setObjectName("status_cb")
        self.status_cb.addItem("")
        self.status_cb.addItem("")
        self.status_cb.addItem("")
        self.status_cb.addItem("")
        self.status_cb.addItem("")
        self.verticalLayout_2.addWidget(self.status_cb)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.update_btn = QtWidgets.QPushButton(b_ud_Form)
        self.update_btn.setObjectName("update_btn")
        self.horizontalLayout_4.addWidget(self.update_btn)
        self.delete_btn = QtWidgets.QPushButton(b_ud_Form)
        self.delete_btn.setObjectName("delete_btn")
        self.horizontalLayout_4.addWidget(self.delete_btn)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.sst_btn = QtWidgets.QPushButton(b_ud_Form)
        self.sst_btn.setObjectName("sst_btn")
        self.verticalLayout_5.addWidget(self.sst_btn)
        self.gridLayout.addLayout(self.verticalLayout_5, 0, 0, 1, 1)

        self.retranslateUi(b_ud_Form)
        QtCore.QMetaObject.connectSlotsByName(b_ud_Form)

    def retranslateUi(self, b_ud_Form):
        _translate = QtCore.QCoreApplication.translate
        b_ud_Form.setWindowTitle(_translate("b_ud_Form", "详情"))
        self.load_photo_btn.setText(_translate("b_ud_Form", "载入书籍封面"))
        self.label_6.setText(_translate("b_ud_Form", "序号："))
        self.label_7.setText(_translate("b_ud_Form", "编号："))
        self.label_8.setText(_translate("b_ud_Form", "书名："))
        self.label_11.setText(_translate("b_ud_Form", "作者："))
        self.label_9.setText(_translate("b_ud_Form", "出版社："))
        self.label_10.setText(_translate("b_ud_Form", "出版日期："))
        self.label_12.setText(_translate("b_ud_Form", "ISBN书号："))
        self.label_13.setText(_translate("b_ud_Form", "语言："))
        self.label_14.setText(_translate("b_ud_Form", "页数："))
        self.label_15.setText(_translate("b_ud_Form", "价格："))
        self.label_17.setText(_translate("b_ud_Form", "入馆日期："))
        self.label_16.setText(_translate("b_ud_Form", "内容简介："))
        self.label_19.setText(_translate("b_ud_Form", "图书状态："))
        self.datepress_le.setPlaceholderText(_translate("b_ud_Form", "格式：yy-mm-dd"))
        self.language_cb.setItemText(0, _translate("b_ud_Form", "中文"))
        self.language_cb.setItemText(1, _translate("b_ud_Form", "英文"))
        self.language_cb.setItemText(2, _translate("b_ud_Form", "日文"))
        self.language_cb.setItemText(3, _translate("b_ud_Form", "俄文"))
        self.language_cb.setItemText(4, _translate("b_ud_Form", "德文"))
        self.language_cb.setItemText(5, _translate("b_ud_Form", "法文"))
        self.dateln_le.setText(_translate("b_ud_Form", "更新为当前时间"))
        self.dateln_cb.setText(_translate("b_ud_Form", "更新"))
        self.status_cb.setItemText(0, _translate("b_ud_Form", "在馆"))
        self.status_cb.setItemText(1, _translate("b_ud_Form", "借出"))
        self.status_cb.setItemText(2, _translate("b_ud_Form", "遗失"))
        self.status_cb.setItemText(3, _translate("b_ud_Form", "变卖"))
        self.status_cb.setItemText(4, _translate("b_ud_Form", "销毁"))
        self.update_btn.setText(_translate("b_ud_Form", "更新信息"))
        self.delete_btn.setText(_translate("b_ud_Form", "删除图书"))
        self.sst_btn.setText(_translate("b_ud_Form", "预约借书"))

import img_rcc_rc
