# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_room_win.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_user_room_Form(object):
    def setupUi(self, user_room_Form):
        user_room_Form.setObjectName("user_room_Form")
        user_room_Form.resize(427, 251)
        self.gridLayout = QtWidgets.QGridLayout(user_room_Form)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.user_photo = QtWidgets.QLabel(user_room_Form)
        self.user_photo.setFrameShape(QtWidgets.QFrame.Box)
        self.user_photo.setText("")
        self.user_photo.setPixmap(QtGui.QPixmap(":/Icon/load.png"))
        self.user_photo.setAlignment(QtCore.Qt.AlignCenter)
        self.user_photo.setObjectName("user_photo")
        self.horizontalLayout_2.addWidget(self.user_photo)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(user_room_Form)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(user_room_Form)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(user_room_Form)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_11 = QtWidgets.QLabel(user_room_Form)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.label_4 = QtWidgets.QLabel(user_room_Form)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(user_room_Form)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(user_room_Form)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(user_room_Form)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_9 = QtWidgets.QLabel(user_room_Form)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(user_room_Form)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.label_12 = QtWidgets.QLabel(user_room_Form)
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.id = QtWidgets.QLabel(user_room_Form)
        self.id.setObjectName("id")
        self.verticalLayout_2.addWidget(self.id)
        self.name = QtWidgets.QLabel(user_room_Form)
        self.name.setObjectName("name")
        self.verticalLayout_2.addWidget(self.name)
        self.sex = QtWidgets.QLabel(user_room_Form)
        self.sex.setObjectName("sex")
        self.verticalLayout_2.addWidget(self.sex)
        self.type = QtWidgets.QLabel(user_room_Form)
        self.type.setObjectName("type")
        self.verticalLayout_2.addWidget(self.type)
        self.dept = QtWidgets.QLabel(user_room_Form)
        self.dept.setObjectName("dept")
        self.verticalLayout_2.addWidget(self.dept)
        self.phone = QtWidgets.QLabel(user_room_Form)
        self.phone.setObjectName("phone")
        self.verticalLayout_2.addWidget(self.phone)
        self.email = QtWidgets.QLabel(user_room_Form)
        self.email.setObjectName("email")
        self.verticalLayout_2.addWidget(self.email)
        self.date = QtWidgets.QLabel(user_room_Form)
        self.date.setObjectName("date")
        self.verticalLayout_2.addWidget(self.date)
        self.status = QtWidgets.QLabel(user_room_Form)
        self.status.setObjectName("status")
        self.verticalLayout_2.addWidget(self.status)
        self.qty = QtWidgets.QLabel(user_room_Form)
        self.qty.setObjectName("qty")
        self.verticalLayout_2.addWidget(self.qty)
        self.roles = QtWidgets.QLabel(user_room_Form)
        self.roles.setObjectName("roles")
        self.verticalLayout_2.addWidget(self.roles)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.psw_change_btn = QtWidgets.QPushButton(user_room_Form)
        self.psw_change_btn.setObjectName("psw_change_btn")
        self.verticalLayout_3.addWidget(self.psw_change_btn)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 1)

        self.retranslateUi(user_room_Form)
        QtCore.QMetaObject.connectSlotsByName(user_room_Form)

    def retranslateUi(self, user_room_Form):
        _translate = QtCore.QCoreApplication.translate
        user_room_Form.setWindowTitle(_translate("user_room_Form", "个人中心"))
        self.label.setText(_translate("user_room_Form", "编号："))
        self.label_2.setText(_translate("user_room_Form", "姓名："))
        self.label_3.setText(_translate("user_room_Form", "性别："))
        self.label_11.setText(_translate("user_room_Form", "类别："))
        self.label_4.setText(_translate("user_room_Form", "单位名称："))
        self.label_5.setText(_translate("user_room_Form", "电话号码："))
        self.label_6.setText(_translate("user_room_Form", "电子邮箱："))
        self.label_7.setText(_translate("user_room_Form", "登记日期："))
        self.label_9.setText(_translate("user_room_Form", "证件状态："))
        self.label_10.setText(_translate("user_room_Form", "已借数量："))
        self.label_12.setText(_translate("user_room_Form", "管理角色："))
        self.id.setText(_translate("user_room_Form", "..."))
        self.name.setText(_translate("user_room_Form", "..."))
        self.sex.setText(_translate("user_room_Form", "..."))
        self.type.setText(_translate("user_room_Form", "..."))
        self.dept.setText(_translate("user_room_Form", "..."))
        self.phone.setText(_translate("user_room_Form", "..."))
        self.email.setText(_translate("user_room_Form", "..."))
        self.date.setText(_translate("user_room_Form", "..."))
        self.status.setText(_translate("user_room_Form", "..."))
        self.qty.setText(_translate("user_room_Form", "..."))
        self.roles.setText(_translate("user_room_Form", "..."))
        self.psw_change_btn.setText(_translate("user_room_Form", "更换密码"))

import img_rcc_rc
